name: Build
"on": workflow_dispatch
jobs:
  build_matrix:
    strategy:
      matrix:
        build_test_nr:
          - 1
          - 2
          - 3
    runs-on: ubuntu-latest
    steps:
      - run: mkdir builds
      - run: echo test > builds/${{ matrix.build_test_nr }}.txt
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: builds/*
  combine:
    runs-on: ubuntu-latest
    needs: build_matrix
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: build-artifacts
          path: builds
      - run: ls builds
